//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrivateLibrary.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookLanguage
    {
        public int BookLanguage_Id { get; set; }
        public int Book_Id { get; set; }
        public int Language_Id { get; set; }
    
        public virtual BookCorrect BookCorrect { get; set; }
        public virtual Language Language { get; set; }
    }
}
